# Generated by Django 5.0.2 on 2024-03-02 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stripe_item', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='currency',
            field=models.CharField(choices=[('USD', 'Usd'), ('RUB', 'Rub')], default='USD', max_length=3),
        ),
    ]
