# Generated by Django 5.0.2 on 2024-03-02 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stripe_item', '0003_alter_item_currency_alter_item_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='currency',
            field=models.CharField(choices=[('USD', '$'), ('EUR', '€')], default='USD', max_length=3),
        ),
    ]
